import { readFileSync } from "node:fs";
import { pathToFileURL } from "node:url";

/**
 * The version PR: what prepare-release.yml opens, and what release-trigger.yml
 * reads back once it merges.
 *
 * `main` takes changes only through a reviewed pull request, so a release no
 * longer writes its own version commit. It arrives as this PR instead, and the
 * release's choices ride in its body as checkboxes. Whoever merges can still
 * change them by ticking a box, and the trigger reads whatever the body says
 * at that point.
 */

export const VERSION_PR_BRANCH = "release/version-packages";
export const VERSION_PR_TITLE_PREFIX = "chore(release): version packages";

const OPTIONS = [
  ["deploy_backend_prod", "Deploy the backend to production"],
  ["deploy_webapp", "Deploy the webapp to production"],
  [
    "skip_verify",
    "Release as soon as this merges, without waiting for green checks (skip_verify)",
  ],
];

/** `releases` is `changeset status` output: `{ name, type, newVersion }`. */
export function versionPrTitle(releases) {
  const bumped = releases.filter((r) => r.type !== "none");
  const inspector = bumped.find((r) => r.name === "@mcpjam/inspector");
  const label = inspector
    ? inspector.newVersion
    : bumped.map((r) => `${r.name} ${r.newVersion}`).join(", ");
  return `${VERSION_PR_TITLE_PREFIX} (${label})`;
}

export function renderReleaseOptions(options) {
  return OPTIONS.map(
    ([key, label]) =>
      `- [${options[key] ? "x" : " "}] ${label} <!-- release-option:${key} -->`
  ).join("\n");
}

/**
 * Reads the checkboxes back. An option whose line is missing, or was edited
 * out of shape, reads as unchecked: a deploy nobody can see asked for must
 * not happen.
 */
export function parseReleaseOptions(body) {
  const options = Object.fromEntries(OPTIONS.map(([key]) => [key, false]));
  const line = /^\s*[-*]\s*\[([ xX])\].*<!--\s*release-option:(\w+)\s*-->/gm;
  for (const [, mark, key] of (body ?? "").matchAll(line)) {
    if (key in options) options[key] = mark !== " ";
  }
  return options;
}

export function versionPrBody({ releases, options, runUrl, sourceSha }) {
  // Release refuses a webapp deploy when there is no Inspector version to
  // deploy, so a packages-only PR never offers one ticked.
  const shipsInspector = releases.some(
    (r) => r.name === "@mcpjam/inspector" && r.type !== "none"
  );
  const offered = {
    ...options,
    deploy_webapp: options.deploy_webapp && shipsInspector,
  };
  const versions = releases
    .filter((r) => r.type !== "none")
    .map((r) => `- \`${r.name}\` ${r.oldVersion} → **${r.newVersion}**`)
    .join("\n");
  return `Versions the pending changesets for the next release.

${versions}

Merging this **is** the release. Once \`main\` is green (Tests, Build and Test and Deploy Staging on the same commit), or right away if skip_verify is ticked below, Release runs by itself: it publishes these versions to npm, deploys what is ticked below, tags the commit and publishes the GitHub release. Nothing is pushed back to \`main\`.

${renderReleaseOptions(offered)}

Only versions, changelogs, the consumed \`.changeset\` files and \`package-lock.json\` change. Generated by [Prepare release](${runUrl}) from \`${sourceSha}\`. If this falls behind \`main\`, updating the branch is fine; running Prepare release again instead also versions any changesets merged since.`;
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  // node release-pr.mjs <changeset status.json>
  // Prints { branch, title, body } for prepare-release.yml.
  const { releases } = JSON.parse(readFileSync(process.argv[2], "utf8"));
  const env = process.env;
  console.log(
    JSON.stringify({
      branch: VERSION_PR_BRANCH,
      title: versionPrTitle(releases),
      body: versionPrBody({
        releases,
        options: {
          deploy_backend_prod: env.DEPLOY_BACKEND_PROD === "true",
          deploy_webapp: env.DEPLOY_WEBAPP === "true",
          skip_verify: env.SKIP_VERIFY === "true",
        },
        runUrl: env.RUN_URL,
        sourceSha: env.SOURCE_SHA,
      }),
    })
  );
}
