/**
 * The v2 run verdict AGGREGATOR, and the adapter that turns one iteration's
 * evidence into the trial observation it consumes.
 *
 * This module is browser-safe and intentionally has no node-only deps.
 *
 * `./verdict-policy.ts` is the contract — shapes, vocabularies, validators —
 * and deliberately ships no aggregator. The backend has had one all along
 * (`convex/lib/evalVerdictPolicy.ts#aggregateEvalRunVerdict`), called by both
 * hosted and SDK-ingest finalization. A LOCAL producer — `runSuiteFile`, which
 * decides a run with no backend involved — needs the same arithmetic, and this
 * is it: a hand mirror of the backend's pure dependency closure, not a
 * re-derivation. The messages a refusal carries are the backend's too, so a
 * malformed input is refused for the same reason on both sides.
 *
 * ── How the two stay one policy ─────────────────────────────────────────────
 *
 * Two implementations of one policy drift silently while each keeps passing
 * its own tests, so both are held to shared, generated ground truth:
 *
 *   - `tests/fixtures/eval-verdict-policy-parity-fixtures.json` pins the
 *     per-case roll-up (its `aggregation` cohort), and
 *   - `tests/fixtures/eval-verdict-run-aggregation-parity-fixtures.json`,
 *     OWNED and generated by mcpjam-backend from its aggregator, pins whole
 *     runs — full expected decisions — plus the finalization adapter's reading
 *     of iteration evidence.
 *
 * Both are byte-for-byte copies; neither is edited here. A change to the
 * arithmetic is a change to BOTH repos in step, regenerated on the backend.
 *
 * ── What is ported, and what is not ─────────────────────────────────────────
 *
 * Ported: the input checks the aggregator runs (policy, identity and caps,
 * configured trials, thresholds, lifecycle statuses), the arithmetic, the
 * reason derivation and order, and the finalization adapter
 * (`evalV2IterationHasEvaluatorError`, `evalV2TrialObservation`).
 *
 * The backend's hand-written decision validator is NOT ported: the SDK already
 * has one, `evalVerdictDecisionSchema`, proven equivalent by the per-case
 * corpus. Every decision this module returns is parsed by it first — a
 * producer must never emit what its own contract refuses to read back. Only
 * the two identity rules of that validator a producer can trip from its INPUT
 * (a `caseId` outside the opaque-id charset, a malformed execution variant) are
 * checked explicitly, with the backend's messages, ahead of that parse.
 */

import { isRequiredRole } from "../predicates/policy.js";
import type { IterationStatus } from "./chain.js";
import {
  MAX_REPETITIONS,
  MAX_SUITE_FILE_CASES,
  MAX_SUITE_FILE_TITLE_CHARS,
} from "./suite-file.js";
import { Z_95, wilsonInterval } from "../compare-stats.js";
import {
  EVAL_TRIAL_EXCLUSION_REASONS,
  EVAL_VERDICT_DECISION_REASONS,
  EVAL_VERDICT_POLICY_VERSION,
  MAX_EVAL_CASE_AGGREGATIONS,
  evalCaseAggregationKey,
  evalExecutionVariantSchema,
  evalVerdictDecisionSchema,
  type EvalCaseVerdictAggregation,
  type EvalExecutionVariant,
  type EvalRateMeasurement,
  type EvalRunVerdict,
  type EvalTrialExclusionReason,
  type EvalTrialExclusions,
  type EvalValidityDecisionReason,
  type EvalVerdictDecision,
  type EvalVerdictDecisionReason,
  type EvalVerdictValidity,
  type ResolvedEvalValidityPolicy,
} from "./verdict-policy.js";

// ── refusals ─────────────────────────────────────────────────────────────────

/**
 * Malformed v2 evidence or policy, refused rather than aggregated.
 *
 * A caller turns this into an `inconclusive` run with an integrity reason —
 * never into a legacy fallback, which would restate v2 evidence under v1
 * semantics and call it a result.
 */
export class EvalVerdictAggregationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "EvalVerdictAggregationError";
  }
}

function fail(message: string): never {
  throw new EvalVerdictAggregationError(
    `Invalid eval verdict policy payload: ${message}`
  );
}

function failFinalization(message: string): never {
  throw new EvalVerdictAggregationError(`eval verdict v2: ${message}`);
}

// ── input checks (mirror convex/lib/evalVerdictPolicy.ts) ────────────────────

const POLICY_FIELDS = [
  "coverage",
  "minCompletionRate",
  "maxEvaluatorErrorRate",
] as const;
const COVERAGE_DEFAULT_FIELDS = ["kind", "minGradeableTrials"] as const;
const COVERAGE_EXPLICIT_FIELDS = ["kind", "minEligibleTrials"] as const;
const EXECUTION_VARIANT_FIELDS = ["model", "provider"] as const;

/** What an omitted `minEligibleTrials` pins the gradeable floor to. */
const DEFAULT_MIN_GRADEABLE_TRIALS = 1;

const OPAQUE_ID_PATTERN = /^[A-Za-z0-9_-]{1,128}$/;

function assertObject(value: unknown, label: string): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    fail(`${label} must be an object`);
  }
  return value as Record<string, unknown>;
}

function assertClosed(
  value: Record<string, unknown>,
  allowed: readonly string[],
  label: string
): void {
  for (const key of Object.keys(value)) {
    if (!allowed.includes(key)) {
      fail(
        `${label} has unknown field "${key}" (allowed: ${allowed.join(", ")})`
      );
    }
  }
}

/** A count of trials: a non-negative integer. */
function assertTrialCount(value: unknown, label: string): number {
  if (typeof value !== "number" || !Number.isInteger(value) || value < 0) {
    fail(`${label} must be a non-negative integer`);
  }
  return value;
}

/** A rate or a threshold: a finite real in [0,1]. NEVER a percent. */
function assertFraction(value: unknown, label: string): number {
  if (typeof value !== "number" || !Number.isFinite(value)) {
    fail(`${label} must be a finite number`);
  }
  if (value < 0 || value > 1) {
    fail(
      `${label} must be a fraction in [0,1] — v2 thresholds are fractions, ` +
        `never percentages (received ${value})`
    );
  }
  return value;
}

function assertValidResolvedEvalValidityPolicy(
  value: unknown,
  label = "validity policy"
): void {
  const policy = assertObject(value, label);
  assertClosed(policy, POLICY_FIELDS, label);
  assertFraction(policy.minCompletionRate, `${label}.minCompletionRate`);
  assertFraction(
    policy.maxEvaluatorErrorRate,
    `${label}.maxEvaluatorErrorRate`
  );

  const coverage = assertObject(policy.coverage, `${label}.coverage`);
  if (coverage.kind === "allConfiguredTrialsAttempted") {
    assertClosed(coverage, COVERAGE_DEFAULT_FIELDS, `${label}.coverage`);
    if (coverage.minGradeableTrials !== DEFAULT_MIN_GRADEABLE_TRIALS) {
      fail(
        `${label}.coverage.minGradeableTrials is pinned to ` +
          `${DEFAULT_MIN_GRADEABLE_TRIALS} under the default coverage rule`
      );
    }
    return;
  }
  if (coverage.kind !== "minEligibleTrials") {
    fail(
      `${label}.coverage.kind must be "allConfiguredTrialsAttempted" or ` +
        `"minEligibleTrials"`
    );
  }
  assertClosed(coverage, COVERAGE_EXPLICIT_FIELDS, `${label}.coverage`);
  const minEligible = assertTrialCount(
    coverage.minEligibleTrials,
    `${label}.coverage.minEligibleTrials`
  );
  if (minEligible < 1) {
    fail(`${label}.coverage.minEligibleTrials must be at least 1`);
  }
}

function assertValidExecutionVariant(value: unknown, label: string): void {
  const variant = assertObject(value, label);
  assertClosed(variant, EXECUTION_VARIANT_FIELDS, label);
  for (const field of ["model", "provider"] as const) {
    const entry = variant[field];
    if (field === "provider" && entry === undefined) continue;
    if (typeof entry !== "string" || entry.length === 0) {
      fail(`${label}.${field} must be a non-empty string`);
    }
    if (entry.length > MAX_SUITE_FILE_TITLE_CHARS) {
      fail(
        `${label}.${field} must be at most ${MAX_SUITE_FILE_TITLE_CHARS} characters`
      );
    }
  }
}

/**
 * The identity and cap rules for a set of case aggregates — checked on the
 * INPUTS, so the failure names what the caller sent.
 *
 * All four rules stop one silent collapse each: a duplicate (caseId, variant)
 * key would double a denominator; a case carrying both a variant-keyed and an
 * unkeyed aggregate would treat omission as a wildcard (it means "this run did
 * not fan out"); and the two caps bound what one decision can summarize.
 */
function assertDistinctCaseAggregationIdentities(
  entries: ReadonlyArray<{
    caseId: string;
    executionVariant?: EvalExecutionVariant;
  }>,
  label = "cases"
): void {
  if (entries.length > MAX_EVAL_CASE_AGGREGATIONS) {
    fail(
      `${entries.length} ${label} aggregations exceeds the maximum of ` +
        `${MAX_EVAL_CASE_AGGREGATIONS}`
    );
  }
  const seenKeys = new Set<string>();
  const variantedCases = new Set<string>();
  const unvariantedCases = new Set<string>();
  for (const entry of entries) {
    const key = evalCaseAggregationKey(entry);
    if (seenKeys.has(key)) {
      fail(
        `case "${entry.caseId}" already has an aggregate for this execution ` +
          `variant; a fan-out run reports ONE row per provider/model pair`
      );
    }
    seenKeys.add(key);
    (entry.executionVariant ? variantedCases : unvariantedCases).add(
      entry.caseId
    );
  }
  for (const caseId of variantedCases) {
    if (unvariantedCases.has(caseId)) {
      fail(
        `case "${caseId}" mixes variant-keyed and unkeyed aggregates: an ` +
          `omitted executionVariant means "this run did not fan out", not ` +
          `"any variant", so the two cannot describe the same case`
      );
    }
  }
  const distinctCases = new Set(entries.map((entry) => entry.caseId)).size;
  if (distinctCases > MAX_SUITE_FILE_CASES) {
    fail(
      `${distinctCases} distinct cases exceeds the portable suite-file ` +
        `maximum of ${MAX_SUITE_FILE_CASES}`
    );
  }
}

/**
 * The two rules of the decision validator a producer can trip from its input,
 * with the backend validator's own messages — see the module docblock.
 */
function assertProducibleCaseIdentity(
  entry: EvalCaseVerdictAggregation,
  label: string
): void {
  if (
    typeof entry.caseId !== "string" ||
    !OPAQUE_ID_PATTERN.test(entry.caseId)
  ) {
    fail(`${label}.caseId must match ${OPAQUE_ID_PATTERN.source}`);
  }
  if (entry.executionVariant !== undefined) {
    assertValidExecutionVariant(
      entry.executionVariant,
      `${label}.executionVariant`
    );
  }
}

// ── the aggregator ───────────────────────────────────────────────────────────

/**
 * One trial as the producer observed it.
 *
 * `status` is the LIFECYCLE (`ITERATION_STATUSES`), `taskVerdict` the graded
 * outcome, and `evaluatorError` says the GRADER broke. All three are supplied
 * explicitly: deriving a task verdict from a lifecycle status is the
 * "we never ran it" → "it passed" collapse this vocabulary exists to prevent,
 * and nothing here reads a legacy `passed` boolean.
 */
export type EvalTrialObservation = {
  status: IterationStatus;
  taskVerdict?: "passed" | "failed";
  evaluatorError?: boolean;
};

/** One (case, execution variant)'s configured population and its trials. */
export type EvalCaseVerdictInput = {
  caseId: string;
  executionVariant?: EvalExecutionVariant;
  configuredTrials: number;
  effectivePassThreshold: number;
  trials: readonly EvalTrialObservation[];
};

/**
 * Statuses that mean the trial never BEGAN, or was withdrawn.
 *
 * A `running` trial has begun, so it stays in the attempted denominator and
 * its unfinished state lowers the completion rate. A `cancelled` one is
 * withdrawn from EVERY denominator: the harness took its outcome away.
 */
const NOT_ATTEMPTED_STATUSES: readonly IterationStatus[] = [
  "pending",
  "skipped",
  "cancelled",
];

/** Which exclusion reason a non-gradeable trial is recorded under. */
function exclusionReasonFor(
  trial: EvalTrialObservation
): EvalTrialExclusionReason {
  switch (trial.status) {
    case "pending":
    case "running":
      return "notTerminal";
    case "skipped":
      return "skipped";
    case "setup_failed":
      return "setupFailed";
    case "cancelled":
      return "cancelled";
    case "timed_out":
      return "timedOut";
    case "failed":
      return "executionFailed";
    case "completed":
      if (trial.evaluatorError) return "evaluatorError";
      // falls through to the malformed-evidence refusal below
      break;
    default:
      // Exhaustive at COMPILE time; this is the runtime edge — evidence from
      // a newer producer, or a status since retired. An unlabelled trial in a
      // tally would make the arithmetic disagree with its own counts.
      fail(
        `trial carries unknown lifecycle status ` +
          `${JSON.stringify(trial.status)}; v2 evidence must use the mirrored ` +
          `iteration-status vocabulary`
      );
  }
  // A completed trial with neither a task verdict nor an evaluator error is
  // MALFORMED evidence, not an outcome: guessing a reason is how a grader
  // failure becomes a server failure, or the reverse.
  fail(
    `trial for a completed iteration carries neither a task verdict nor an ` +
      `evaluator error; v2 evidence must say which`
  );
}

function tallyExclusion(
  tally: EvalTrialExclusions,
  reason: EvalTrialExclusionReason
): void {
  tally[reason] = (tally[reason] ?? 0) + 1;
}

function measure(
  numerator: number,
  denominator: number,
  exclusions: EvalTrialExclusions
): EvalRateMeasurement {
  if (denominator === 0) {
    return {
      state: "notMeasured",
      value: null,
      numerator: 0,
      denominator: 0,
      exclusions,
    };
  }
  return {
    state: "measured",
    value: numerator / denominator,
    numerator,
    denominator,
    exclusions,
  };
}

/** The per-case counts the suite-level validity phase needs. */
type CaseTally = {
  aggregation: EvalCaseVerdictAggregation;
  completedTrials: number;
  evaluatorErrorTrials: number;
  attemptExclusions: EvalTrialExclusions;
};

function aggregateCase(input: EvalCaseVerdictInput): CaseTally {
  if (
    !Number.isInteger(input.configuredTrials) ||
    input.configuredTrials < 1 ||
    input.configuredTrials > MAX_REPETITIONS
  ) {
    fail(
      `configuredTrials for case "${input.caseId}" must be an integer within ` +
        `1..${MAX_REPETITIONS} (per execution variant)`
    );
  }
  assertFraction(
    input.effectivePassThreshold,
    `case "${input.caseId}" effectivePassThreshold`
  );

  let attempted = 0;
  let eligible = 0;
  let passed = 0;
  let failedTrials = 0;
  let completed = 0;
  let evaluatorErrors = 0;
  // Exclusions travel PER RATE: the trials removed from an eligibility
  // denominator are not the ones removed from a completion denominator.
  const eligibilityExclusions: EvalTrialExclusions = {};
  const attemptExclusions: EvalTrialExclusions = {};

  for (const trial of input.trials) {
    const isAttempted = !NOT_ATTEMPTED_STATUSES.includes(trial.status);
    if (isAttempted) attempted += 1;
    if (trial.status === "completed") completed += 1;
    if (trial.status === "completed" && trial.evaluatorError) {
      evaluatorErrors += 1;
    }

    const gradeable =
      trial.status === "completed" &&
      !trial.evaluatorError &&
      trial.taskVerdict !== undefined;
    if (gradeable) {
      eligible += 1;
      if (trial.taskVerdict === "passed") passed += 1;
      else failedTrials += 1;
      continue;
    }

    const reason = exclusionReasonFor(trial);
    tallyExclusion(eligibilityExclusions, reason);
    if (!isAttempted) tallyExclusion(attemptExclusions, reason);
  }

  if (input.trials.length > input.configuredTrials) {
    fail(
      `case "${input.caseId}" reported ${input.trials.length} trials for ` +
        `${input.configuredTrials} configured`
    );
  }
  // Configured-but-unreported trials never began: the same thing a `pending`
  // row says, recorded the same way, so a producer that omits stubs and one
  // that writes them produce identical decisions.
  const unreported = input.configuredTrials - input.trials.length;
  if (unreported > 0) {
    eligibilityExclusions.notTerminal =
      (eligibilityExclusions.notTerminal ?? 0) + unreported;
    attemptExclusions.notTerminal =
      (attemptExclusions.notTerminal ?? 0) + unreported;
  }

  const passRate = measure(passed, eligible, eligibilityExclusions);
  const completionRate = measure(completed, attempted, attemptExclusions);
  const observedStability = measure(
    Math.max(passed, failedTrials),
    eligible,
    eligibilityExclusions
  );

  const verdict: EvalRunVerdict =
    eligible === 0
      ? "inconclusive"
      : passRate.value !== null &&
          passRate.value >= input.effectivePassThreshold
        ? "passed"
        : "failed";
  const reason: EvalVerdictDecisionReason =
    eligible === 0
      ? "caseHasNoEligibleTrials"
      : verdict === "passed"
        ? "casePassRateMetThreshold"
        : "casePassRateBelowThreshold";

  return {
    aggregation: {
      caseId: input.caseId,
      ...(input.executionVariant
        ? { executionVariant: input.executionVariant }
        : {}),
      configuredTrials: input.configuredTrials,
      attemptedTrials: attempted,
      eligibleTrials: eligible,
      passedTrials: passed,
      failedTrials,
      effectivePassThreshold: input.effectivePassThreshold,
      passRate,
      completionRate,
      observedStability,
      mixedVerdict: passed > 0 && failedTrials > 0,
      verdict,
      reason,
    },
    completedTrials: completed,
    evaluatorErrorTrials: evaluatorErrors,
    attemptExclusions,
  };
}

/** Roll ONE case's trials up — the per-case corpus's `aggregation` cohort. */
export function aggregateEvalCaseVerdict(
  input: EvalCaseVerdictInput
): EvalCaseVerdictAggregation {
  return aggregateCase(input).aggregation;
}

function mergeExclusions(
  into: EvalTrialExclusions,
  from: EvalTrialExclusions
): void {
  for (const reason of EVAL_TRIAL_EXCLUSION_REASONS) {
    const count = from[reason];
    if (count === undefined) continue;
    into[reason] = (into[reason] ?? 0) + count;
  }
}

/**
 * The reasons a failed validity phase produces: the FAILED checks, all of them
 * and only them.
 */
function expectedValidityReasons(
  validity: EvalVerdictValidity,
  completionMet: boolean,
  evaluatorMet: boolean,
  everyCaseMeasured: boolean
): EvalValidityDecisionReason[] {
  const reasons: EvalValidityDecisionReason[] = [];
  if (validity.policy.coverage.kind === "allConfiguredTrialsAttempted") {
    if (validity.attemptedTrials !== validity.configuredTrials) {
      reasons.push("configuredTrialsNotAttempted");
    }
    if (validity.eligibleTrials < validity.policy.coverage.minGradeableTrials) {
      reasons.push("noGradeableTrials");
    }
  } else if (
    validity.eligibleTrials < validity.policy.coverage.minEligibleTrials
  ) {
    reasons.push("eligibleTrialsBelowMinimum");
  }
  if (validity.completionRate.state !== "measured") {
    reasons.push("completionRateNotMeasured");
  } else if (!completionMet) {
    reasons.push("completionRateBelowMinimum");
  }
  if (validity.evaluatorErrorRate.state !== "measured") {
    reasons.push("evaluatorErrorRateNotMeasured");
  } else if (!evaluatorMet) {
    reasons.push("evaluatorErrorRateAboveMaximum");
  }
  if (!everyCaseMeasured) reasons.push("caseHasNoEligibleTrials");
  return reasons;
}

function taskVerdictFromCases(
  cases: readonly EvalCaseVerdictAggregation[]
): EvalRunVerdict {
  if (cases.some((entry) => entry.verdict === "inconclusive")) {
    return "inconclusive";
  }
  if (cases.some((entry) => entry.verdict === "failed")) return "failed";
  return "passed";
}

/**
 * Parse the produced decision with the SDK's own contract validator before
 * returning it: a producer must never emit what its contract refuses to read
 * back. A refusal here is a bug in this module, never in the caller's input —
 * every input rule is checked above with its own message.
 */
function selfChecked(decision: EvalVerdictDecision): EvalVerdictDecision {
  decision.cases.forEach((entry, index) =>
    assertProducibleCaseIdentity(entry, `cases[${index}]`)
  );
  const parsed = evalVerdictDecisionSchema.safeParse(decision);
  if (!parsed.success) {
    fail(
      `the produced decision violates the verdict contract: ${parsed.error.issues
        .map((issue) => `${issue.path.join(".")}: ${issue.message}`)
        .join("; ")}`
    );
  }
  return decision;
}

/**
 * THE v2 decision — the same function, rule for rule, that hosted and SDK
 * ingest finalization call on the backend.
 *
 * Pure: no clock, no I/O. Throws {@link EvalVerdictAggregationError} on
 * malformed evidence or policy (a completed trial with no verdict and no
 * evaluator error, a threshold outside [0,1], more trials than configured, a
 * duplicate identity), which a caller turns into an `inconclusive` run with an
 * integrity reason rather than a fallback.
 */
export function aggregateEvalRunVerdict(args: {
  policy: ResolvedEvalValidityPolicy;
  cases: readonly EvalCaseVerdictInput[];
}): EvalVerdictDecision {
  assertValidResolvedEvalValidityPolicy(args.policy);
  if (args.cases.length === 0) {
    fail("a v2 decision needs at least one case aggregate");
  }
  // Identity and caps BEFORE any arithmetic, on the INPUTS, so the failure
  // names what the caller sent rather than a decision already built.
  assertDistinctCaseAggregationIdentities(args.cases);

  const tallies = args.cases.map(aggregateCase);
  const cases = tallies.map((tally) => tally.aggregation);

  let configured = 0;
  let attempted = 0;
  let eligible = 0;
  let completed = 0;
  let evaluatorErrors = 0;
  const attemptExclusions: EvalTrialExclusions = {};
  for (const tally of tallies) {
    configured += tally.aggregation.configuredTrials;
    attempted += tally.aggregation.attemptedTrials;
    eligible += tally.aggregation.eligibleTrials;
    completed += tally.completedTrials;
    evaluatorErrors += tally.evaluatorErrorTrials;
    mergeExclusions(attemptExclusions, tally.attemptExclusions);
  }

  const completionRate = measure(completed, attempted, attemptExclusions);
  const evaluatorErrorRate = measure(
    evaluatorErrors,
    attempted,
    attemptExclusions
  );

  const coverageMet =
    args.policy.coverage.kind === "minEligibleTrials"
      ? eligible >= args.policy.coverage.minEligibleTrials
      : attempted === configured &&
        eligible >= args.policy.coverage.minGradeableTrials;
  const completionMet =
    completionRate.state === "measured" &&
    completionRate.value >= args.policy.minCompletionRate;
  const evaluatorMet =
    evaluatorErrorRate.state === "measured" &&
    evaluatorErrorRate.value <= args.policy.maxEvaluatorErrorRate;
  const everyCaseMeasured = cases.every((entry) => entry.eligibleTrials > 0);
  const holds =
    coverageMet && completionMet && evaluatorMet && everyCaseMeasured;

  const validity: EvalVerdictValidity = {
    policy: args.policy,
    holds,
    configuredTrials: configured,
    attemptedTrials: attempted,
    eligibleTrials: eligible,
    completionRate,
    evaluatorErrorRate,
  };

  if (!holds) {
    const reasons = expectedValidityReasons(
      validity,
      completionMet,
      evaluatorMet,
      everyCaseMeasured
    ).sort(
      (left, right) =>
        EVAL_VERDICT_DECISION_REASONS.indexOf(left) -
        EVAL_VERDICT_DECISION_REASONS.indexOf(right)
    );
    return selfChecked({
      verdictPolicyVersion: EVAL_VERDICT_POLICY_VERSION,
      verdict: "inconclusive",
      reasons,
      validity,
      cases,
    });
  }

  const verdict = taskVerdictFromCases(cases);
  return selfChecked({
    verdictPolicyVersion: EVAL_VERDICT_POLICY_VERSION,
    verdict,
    reasons: [
      verdict === "passed"
        ? "allMeasuredCasesMetThreshold"
        : "casePassRateBelowThreshold",
    ],
    validity,
    cases,
  });
}

// ── the finalization adapter (mirror convex/lib/evalVerdictFinalization.ts) ──

/**
 * The iteration evidence a v2 decision reads — the same columns the backend
 * reads off a `testIteration` row: the lifecycle status, the legacy result,
 * and the metadata the scores and their definitions travel in
 * (`metadata.scores`, `metadata.evaluationConfig`, `metadata.scoreIntegrity`).
 */
export type EvalV2IterationEvidence = {
  status: IterationStatus;
  result: "pending" | "passed" | "failed" | "cancelled" | "timed_out";
  metadata?: Record<string, unknown> | undefined;
};

function readDefinitions(
  value: unknown
): Map<string, { role?: string; onError?: string; onSkipped?: string }> {
  const map = new Map<
    string,
    { role?: string; onError?: string; onSkipped?: string }
  >();
  if (typeof value !== "object" || value === null) return map;
  const definitions = (value as Record<string, unknown>).definitions;
  if (!Array.isArray(definitions)) return map;
  for (const definition of definitions) {
    if (typeof definition !== "object" || definition === null) continue;
    const row = definition as Record<string, unknown>;
    if (typeof row.scorerId !== "string") continue;
    map.set(row.scorerId, {
      role: typeof row.role === "string" ? row.role : undefined,
      onError: typeof row.onError === "string" ? row.onError : undefined,
      onSkipped: typeof row.onSkipped === "string" ? row.onSkipped : undefined,
    });
  }
  return map;
}

/**
 * Was this iteration's gating evidence produced by a broken evaluator?
 *
 * Four signals: the score-integrity downgrade; a GATING scorer that reported
 * `error` under `onError: "fail"`; a GATING scorer that reported `skipped`
 * under `onSkipped: "fail"`; and a configured GATING scorer with no row at
 * all, unless its `onSkipped` is `"ignore"`. `not_applicable` counts as
 * represented. Advisory scorers are read for none of this, and metadata with
 * no `evaluationConfig` declares no gating scorer, so nothing can be missing.
 */
export function evalV2IterationHasEvaluatorError(
  metadata: Record<string, unknown> | undefined
): boolean {
  if (metadata === undefined) return false;
  if (metadata.scoreIntegrity === "score_integrity_invalid") return true;

  const definitions = readDefinitions(metadata.evaluationConfig);
  const gatingIds = [...definitions.entries()]
    .filter(([, definition]) => isRequiredRole(definition.role))
    .map(([scorerId]) => scorerId);

  if (gatingIds.length === 0) return false;

  const rows = Array.isArray(metadata.scores) ? metadata.scores : [];

  const represented = new Set<string>();
  for (const score of rows) {
    if (typeof score !== "object" || score === null) continue;
    const row = score as Record<string, unknown>;
    const scorerId = String(row.scorerId);
    const definition = definitions.get(scorerId);
    // No definition ⇒ unknown role, and an unknown role is not assumed
    // gating.
    if (definition === undefined || !isRequiredRole(definition.role)) continue;
    represented.add(scorerId);
    if (row.status === "error" && definition.onError === "fail") return true;
    if (row.status === "skipped" && definition.onSkipped === "fail") {
      return true;
    }
  }

  return gatingIds.some(
    (scorerId) =>
      !represented.has(scorerId) &&
      definitions.get(scorerId)?.onSkipped !== "ignore"
  );
}

/**
 * One iteration's evidence → one trial observation.
 *
 * The status is taken VERBATIM. Only the verdict is derived, and only for a
 * completed iteration: `result: "passed"` on a `timed_out` row describes
 * grading that never finished.
 */
export function evalV2TrialObservation(
  row: EvalV2IterationEvidence
): EvalTrialObservation {
  if (row.status !== "completed") {
    return { status: row.status };
  }
  if (evalV2IterationHasEvaluatorError(row.metadata)) {
    return { status: "completed", evaluatorError: true };
  }
  if (row.result === "passed" || row.result === "failed") {
    return { status: "completed", taskVerdict: row.result };
  }
  failFinalization(
    `a completed iteration carries verdict "${row.result}", which is neither ` +
      `a task verdict nor an evaluator error`
  );
}

// ── per-case trial statistics (mirror convex/lib/evalVerdictPolicy.ts) ──────

/**
 * pass@k, pass^k and a Wilson interval for every case aggregate of a decision —
 * READ-SIDE statistics derived from the decision's own counts. They decide
 * nothing: a case's verdict is `passRate.value >= effectivePassThreshold` and
 * stays exactly that.
 *
 * A hand mirror of the backend's section of the same name, with the same
 * arithmetic in the same operation order, so both sides produce the same
 * IEEE-754 doubles for the same counts. Held to the per-case corpus's
 * `trialStatistics` cohort (hand-computed goldens) and the run corpus's
 * `expectedTrialStatistics` (generated on the backend from real decisions).
 *
 * NOT fields of {@link EvalCaseVerdictAggregation}: published SDKs parse a
 * run's `verdictSummary` with closed schemas, so a field added to the stored
 * decision would break every client already installed. The statistics travel
 * BESIDE the decision (`trialStatistics`), computed on read.
 *
 * The unit is the decision's own rows — case × execution variant. `n` is
 * `eligibleTrials` (infrastructure failures, evaluator errors and unfinished
 * trials are already out of it), `c` is `passedTrials`, and `k = n`, stated on
 * every row: pass@n reads "at least one eligible trial passed", pass^n "every
 * eligible trial passed". {@link evalPassAtK} / {@link evalPassHatK} take any
 * k. `n = 0` makes every statistic `null` (with `k = 0`).
 */
export const EVAL_TRIAL_STATISTICS_UNIT = "caseVariant";
/** The confidence level of {@link evalPassRateWilsonInterval}. */
export const EVAL_TRIAL_STATISTICS_CONFIDENCE = 0.95;
/** {@link Z_95}, under the backend mirror's name. */
export const EVAL_TRIAL_STATISTICS_Z = Z_95;

export type EvalTrialStatisticsInterval = {
  confidence: typeof EVAL_TRIAL_STATISTICS_CONFIDENCE;
  lower: number;
  upper: number;
};

export type EvalCaseTrialStatistics = {
  caseId: string;
  executionVariant?: EvalExecutionVariant;
  /** n — the case aggregate's `eligibleTrials`. */
  eligibleTrials: number;
  /** c — the case aggregate's `passedTrials`. */
  passedTrials: number;
  /** The k both estimators below are taken at: always `eligibleTrials`. */
  k: number;
  /** Unbiased pass@k; `null` when `eligibleTrials` is 0. */
  passAtK: number | null;
  /** Unbiased pass^k; `null` when `eligibleTrials` is 0. */
  passHatK: number | null;
  /** Wilson score interval on `c / n`; `null` when `eligibleTrials` is 0. */
  passRateInterval: EvalTrialStatisticsInterval | null;
};

export type EvalVerdictTrialStatistics = {
  unit: typeof EVAL_TRIAL_STATISTICS_UNIT;
  /**
   * Σ eligibleTrials over every row: the sample a run-over-run comparison is
   * sized by. NOT `summary.total`, whose unit is iterations, cases or case
   * variants depending on which producer wrote it.
   */
  eligibleTrials: number;
  /** Σ passedTrials over every row. */
  passedTrials: number;
  cases: EvalCaseTrialStatistics[];
};

function assertStatisticsCounts(
  eligibleTrials: unknown,
  passedTrials: unknown,
  label: string
): void {
  const eligible = assertTrialCount(eligibleTrials, `${label}.eligibleTrials`);
  const passed = assertTrialCount(passedTrials, `${label}.passedTrials`);
  if (passed > eligible) {
    fail(`${label} passed ${passed} exceeds eligible ${eligible}`);
  }
}

/**
 * C(a, k) / C(n, k) as a running product, never as two binomials (C(100, 50)
 * is far past 2^53). The factors and their ORDER are the backend's, which is
 * what makes the two doubles identical rather than merely close.
 */
function binomialRatio(a: number, n: number, k: number): number {
  if (k > a) return 0;
  let ratio = 1;
  for (let i = 0; i < k; i += 1) ratio *= (a - i) / (n - i);
  return ratio;
}

/** Whether k is estimable from n trials: an integer within 1..n. */
function estimableK(eligibleTrials: number, k: unknown): boolean {
  if (typeof k !== "number" || !Number.isInteger(k)) {
    fail(`k must be an integer (received ${String(k)})`);
  }
  return eligibleTrials > 0 && k >= 1 && k <= eligibleTrials;
}

/**
 * Unbiased pass@k: the probability that at least one of k trials, drawn
 * without replacement from the n eligible ones, passed —
 * `1 − C(n − c, k) / C(n, k)` (Chen et al. 2021).
 *
 *   n=5, c=3, k=2 → 1 − C(2,2)/C(5,2) = 1 − 1/10 = 0.9
 *   n=4, c=1, k=2 → 1 − C(3,2)/C(4,2) = 1 − 3/6  = 0.5
 *   n=5, c=0, k=k → 0;  c=n → 1
 *
 * `null` when it is not estimable: no eligible trials, or k outside 1..n.
 */
export function evalPassAtK(
  eligibleTrials: number,
  passedTrials: number,
  k: number
): number | null {
  assertStatisticsCounts(eligibleTrials, passedTrials, "pass@k");
  if (!estimableK(eligibleTrials, k)) return null;
  return 1 - binomialRatio(eligibleTrials - passedTrials, eligibleTrials, k);
}

/**
 * Unbiased pass^k: the probability that ALL k trials, drawn without
 * replacement from the n eligible ones, passed — `C(c, k) / C(n, k)`.
 *
 *   n=5, c=3, k=2 → C(3,2)/C(5,2) = 3/10 = 0.3
 *   n=4, c=3, k=3 → C(3,3)/C(4,3) = 1/4  = 0.25
 *   k=1 → c/n, the pass rate itself
 *
 * `null` when it is not estimable: no eligible trials, or k outside 1..n.
 */
export function evalPassHatK(
  eligibleTrials: number,
  passedTrials: number,
  k: number
): number | null {
  assertStatisticsCounts(eligibleTrials, passedTrials, "pass^k");
  if (!estimableK(eligibleTrials, k)) return null;
  return binomialRatio(passedTrials, eligibleTrials, k);
}

/**
 * Wilson score interval on `c / n` at 95% — {@link wilsonInterval} itself, the
 * interval the compare gates already use, with the endpoints at c = 0 and
 * c = n pinned to their exact values (0 and 1). The formula reaches them only
 * up to rounding (0/20 gives a lower bound of 1.4e-17), and a reader testing
 * `upper === 1` for "every trial passed" must not be told otherwise.
 */
export function evalPassRateWilsonInterval(
  eligibleTrials: number,
  passedTrials: number
): EvalTrialStatisticsInterval | null {
  assertStatisticsCounts(eligibleTrials, passedTrials, "pass rate interval");
  if (eligibleTrials === 0) return null;
  const interval = wilsonInterval(
    passedTrials,
    eligibleTrials,
    EVAL_TRIAL_STATISTICS_Z
  );
  return {
    confidence: EVAL_TRIAL_STATISTICS_CONFIDENCE,
    lower: passedTrials === 0 ? 0 : interval.lower,
    upper: passedTrials === eligibleTrials ? 1 : interval.upper,
  };
}

/** One case aggregate's statistics, at k = n. */
export function evalCaseTrialStatistics(
  aggregation: Pick<
    EvalCaseVerdictAggregation,
    "caseId" | "executionVariant" | "eligibleTrials" | "passedTrials"
  >
): EvalCaseTrialStatistics {
  const n = aggregation.eligibleTrials;
  const c = aggregation.passedTrials;
  return {
    caseId: aggregation.caseId,
    ...(aggregation.executionVariant
      ? { executionVariant: aggregation.executionVariant }
      : {}),
    eligibleTrials: n,
    passedTrials: c,
    k: n,
    passAtK: evalPassAtK(n, c, n),
    passHatK: evalPassHatK(n, c, n),
    passRateInterval: evalPassRateWilsonInterval(n, c),
  };
}

/**
 * Every case aggregate's statistics, in `decision.cases` order, plus the
 * pooled trial counts a comparison is sized by.
 */
export function evalVerdictTrialStatistics(
  decision: Pick<EvalVerdictDecision, "cases">
): EvalVerdictTrialStatistics {
  const cases = decision.cases.map(evalCaseTrialStatistics);
  let eligibleTrials = 0;
  let passedTrials = 0;
  for (const entry of cases) {
    eligibleTrials += entry.eligibleTrials;
    passedTrials += entry.passedTrials;
  }
  return {
    unit: EVAL_TRIAL_STATISTICS_UNIT,
    eligibleTrials,
    passedTrials,
    cases,
  };
}

const TRIAL_STATISTICS_FIELDS = [
  "unit",
  "eligibleTrials",
  "passedTrials",
  "cases",
] as const;
const TRIAL_STATISTICS_INTERVAL_FIELDS = [
  "confidence",
  "lower",
  "upper",
] as const;
const CASE_TRIAL_STATISTICS_FIELDS = [
  "caseId",
  "executionVariant",
  "eligibleTrials",
  "passedTrials",
  "k",
  "passAtK",
  "passHatK",
  "passRateInterval",
] as const;

/**
 * Refuse a statistics block that is not EXACTLY what its own counts produce —
 * and, given the decision it claims to describe, one whose rows are not that
 * decision's rows. Every value is recomputed and compared exactly, as a rate's
 * `value` is; every object is closed. Throws
 * {@link EvalVerdictAggregationError} with the backend validator's messages.
 */
export function assertValidEvalVerdictTrialStatistics(
  value: unknown,
  decision?: Pick<EvalVerdictDecision, "cases">
): asserts value is EvalVerdictTrialStatistics {
  const label = "trial statistics";
  const statistics = assertObject(value, label);
  assertClosed(statistics, TRIAL_STATISTICS_FIELDS, label);
  if (statistics.unit !== EVAL_TRIAL_STATISTICS_UNIT) {
    fail(`${label}.unit must be "${EVAL_TRIAL_STATISTICS_UNIT}"`);
  }
  if (!Array.isArray(statistics.cases)) {
    fail(`${label}.cases must be an array`);
  }
  const rows = statistics.cases as unknown[];
  if (decision !== undefined && rows.length !== decision.cases.length) {
    fail(
      `${label} has ${rows.length} rows for a decision of ` +
        `${decision.cases.length} case aggregates`
    );
  }
  const recomputedRows = rows.map((raw, index) => {
    const rowLabel = `${label}.cases[${index}]`;
    const row = assertObject(raw, rowLabel);
    assertClosed(row, CASE_TRIAL_STATISTICS_FIELDS, rowLabel);
    if (typeof row.caseId !== "string" || !OPAQUE_ID_PATTERN.test(row.caseId)) {
      fail(`${rowLabel}.caseId must match ${OPAQUE_ID_PATTERN.source}`);
    }
    // The CONTRACT's variant schema rather than this module's input check: a
    // statistics row describes a stored decision, whose variants may carry a
    // `selectionKey`, exactly as the backend validator accepts.
    if (
      row.executionVariant !== undefined &&
      !evalExecutionVariantSchema.safeParse(row.executionVariant).success
    ) {
      fail(`${rowLabel}.executionVariant is not a valid execution variant`);
    }
    assertStatisticsCounts(row.eligibleTrials, row.passedTrials, rowLabel);
    for (const field of ["k", "passAtK", "passHatK", "passRateInterval"]) {
      // Absent is not null: `null` says "not estimable", absence says nothing.
      if (row[field] === undefined) fail(`${rowLabel}.${field} is required`);
    }
    if (row.passRateInterval !== null) {
      const interval = assertObject(
        row.passRateInterval,
        `${rowLabel}.passRateInterval`
      );
      assertClosed(
        interval,
        TRIAL_STATISTICS_INTERVAL_FIELDS,
        `${rowLabel}.passRateInterval`
      );
    }
    const identity = row as unknown as EvalCaseTrialStatistics;
    if (decision !== undefined) {
      const aggregate = decision.cases[index]!;
      if (
        evalCaseAggregationKey(identity) !== evalCaseAggregationKey(aggregate)
      ) {
        fail(
          `${rowLabel} is not the identity of decision.cases[${index}] ` +
            `("${aggregate.caseId}")`
        );
      }
      if (
        identity.eligibleTrials !== aggregate.eligibleTrials ||
        identity.passedTrials !== aggregate.passedTrials
      ) {
        fail(
          `${rowLabel} counts ${identity.passedTrials}/` +
            `${identity.eligibleTrials} are not decision.cases[${index}]'s ` +
            `${aggregate.passedTrials}/${aggregate.eligibleTrials}`
        );
      }
    }
    const expected = evalCaseTrialStatistics(identity);
    if (canonicalStatisticsRow(identity) !== canonicalStatisticsRow(expected)) {
      fail(
        `${rowLabel} is not what its own counts produce at k = n ` +
          `(expected k ${expected.k}, pass@k ${expected.passAtK}, ` +
          `pass^k ${expected.passHatK})`
      );
    }
    return expected;
  });
  const eligible = assertTrialCount(
    statistics.eligibleTrials,
    `${label}.eligibleTrials`
  );
  const passed = assertTrialCount(
    statistics.passedTrials,
    `${label}.passedTrials`
  );
  const sums = recomputedRows.reduce(
    (sum, row) => ({
      eligible: sum.eligible + row.eligibleTrials,
      passed: sum.passed + row.passedTrials,
    }),
    { eligible: 0, passed: 0 }
  );
  if (eligible !== sums.eligible || passed !== sums.passed) {
    fail(
      `${label} totals ${passed}/${eligible} must be the sums over its rows ` +
        `(${sums.passed}/${sums.eligible})`
    );
  }
}

/**
 * Field-order-independent identity of one statistics row. Exact: JSON spells
 * every double in its shortest round-trip form, so two distinct values never
 * compare equal — and a string where a number belongs never does either.
 */
function canonicalStatisticsRow(row: EvalCaseTrialStatistics): string {
  const interval = row.passRateInterval;
  return JSON.stringify([
    row.eligibleTrials,
    row.passedTrials,
    row.k,
    row.passAtK,
    row.passHatK,
    interval === null
      ? null
      : [interval.confidence, interval.lower, interval.upper],
  ]);
}
