/**
 * Durable browser sessions (W2): ensure a live browserd daemon on a desktop
 * computer, replica-independently.
 *
 * The happy path never touches the sandbox: reserve → look up the session row
 * → verify the daemon itself over its authenticated `/v1/status` (liveness +
 * bootId + bearer in one probe) → reuse. Only when the row is missing, stale,
 * or the daemon fails verification does this connect to the sandbox and
 * relaunch: kill any leftover daemon, upload the bundle, boot, ensure the
 * auth-required stream (whose password the stream mints and holds only in
 * memory), and RECORD the result — the record is load-bearing, because the
 * stream password exists nowhere else durable and an unrecorded runtime is
 * one no replica can later find (record failure ⇒ stop the daemon and
 * refuse).
 *
 * Recovery posture is health-check, NOT kill-on-wake: a paused→resumed box
 * keeps its process tree, so a healthy daemon with the recorded bootId is
 * reused as-is and in-flight command idempotency survives.
 *
 * This is orchestration ONLY, in the same injected-seam form as
 * `browser-debug-probe.ts`: every live piece (Convex reserve/sandbox-info,
 * `Sandbox.connect`, the stream bootstrap, the session store) arrives via
 * `BrowserSessionDeps`, so the sequence — and every refusal path — is
 * unit-testable without E2B or the network. The live construction lives in
 * `live-session-deps.ts` (VALIDATE-ON-STAGING).
 */
import type {
  BootBrowserdOptions,
  BrowserdHandle,
  BrowserdSandbox,
} from "./boot-browserd";
import type {
  BrowserdCommandResponse,
  BrowserdStatus,
} from "./browserd-client";
import type { BrowserCommand } from "./protocol";
import type {
  BrowserSessionLookup,
  BrowserSessionRecord,
} from "./browser-sessions-client";
import { withKeyedLock } from "./probe-lock";

/** Where the daemon lives inside the sandbox — the probe's proven recipe. */
export const BROWSERD_SCRIPT_PATH = "/opt/mcpjam/mcpjam-browserd.mjs";
export const BROWSERD_PORT = 8791;
export const BROWSERD_USER_DATA_DIR = "/home/user/.mcpjam-browserd";

/** A `BrowserdClient`, narrowed to what sessions need (fakeable in tests). */
export interface SessionClient {
  status(): Promise<BrowserdStatus>;
  sendCommand(
    command: BrowserCommand,
    expectedBootId?: string,
  ): Promise<BrowserdCommandResponse>;
}

/** The sandbox pieces the ensure path needs, once connected. */
export interface SessionSandbox {
  /** Write the daemon bundle into the sandbox filesystem. */
  writeBundle(path: string, content: Uint8Array): Promise<void>;
  /** The daemon runner `bootBrowserd` drives. */
  browserd: BrowserdSandbox;
  /** Reap any daemon from a previous boot (idempotent; never throws for
   *  "nothing to kill"). Runs before every relaunch so the fixed port and
   *  profile are free. */
  killBrowserd(): Promise<void>;
  /**
   * Ensure the live desktop stream is up with auth required, and return its
   * public URL plus the password ("auth key") the stream minted. The password
   * is generated BY the stream per start and held in memory there — the
   * session row is the only durable copy, which is the whole reason the row
   * caches it.
   */
  ensureStream(): Promise<{ streamUrl: string; streamPassword: string }>;
  /** Release the connection. Never kills the durable computer itself. */
  disconnect(): Promise<void>;
}

/** The session-store functions (browser-sessions-client), injectable. */
export interface SessionStore {
  lookup(args: {
    computerId: string;
    expectedBundleHash: string;
    signal?: AbortSignal;
  }): Promise<BrowserSessionLookup>;
  record(args: {
    computerId: string;
    bootId: string;
    browserdToken: string;
    browserdPort: number;
    publicOrigin: string;
    streamUrl: string;
    streamPassword: string;
    bundleHash: string;
    contextMode: "persistent" | "ephemeral";
    signal?: AbortSignal;
  }): Promise<string | null>;
  touch(args: {
    sessionId: string;
    kind: "command" | "panel";
    signal?: AbortSignal;
  }): Promise<{ counted: boolean }>;
}

export interface BrowserSessionDeps {
  /**
   * Reserve/ensure a desktop computer for this user+project; returns its row
   * id. MUST reserve with `runtimeKind: "desktop-browser"` — the plugin-box
   * precedent (`resolveColocatedPluginBox`) omits the kind and reserves a
   * terminal box, so it cannot be reused verbatim here.
   */
  reserveDesktop(args: {
    bearer: string;
    projectId: string;
    signal?: AbortSignal;
  }): Promise<{ computerId: string }>;
  /** Exchange a computer id for its vendor sandbox id. */
  resolveSandboxId(computerId: string): Promise<string>;
  /** Connect to the sandbox. */
  connect(sandboxId: string): Promise<SessionSandbox>;
  /** Boot browserd (the real `bootBrowserd` in production). */
  boot(
    sandbox: BrowserdSandbox,
    options: BootBrowserdOptions,
  ): Promise<BrowserdHandle>;
  /** Build the client for a daemon at `baseUrl` presenting `bearer`. */
  createClient(baseUrl: string, bearer: string): SessionClient;
  store: SessionStore;
  /** The daemon bundle bytes to upload on a relaunch. */
  bundle(): Uint8Array;
  /** sha256 (hex) of those bytes — the row's `bundleHash` identity. */
  bundleHash(): string;
}

export interface EnsureBrowserSessionArgs {
  /** The USER whose desktop is reserved (their control-plane bearer). */
  bearer: string;
  projectId: string;
  /** Persistent Chrome profile (playground/inspector) unless stated. */
  contextMode?: "persistent" | "ephemeral";
  signal?: AbortSignal;
}

export interface BrowserSessionHandle {
  sessionId: string;
  computerId: string;
  bootId: string;
  client: SessionClient;
  streamUrl: string;
  streamPassword: string;
  contextMode: "persistent" | "ephemeral";
  /** True when an existing daemon was verified and reused (no sandbox I/O). */
  reused: boolean;
}

/**
 * Ensure a verified-live browserd session on this user's desktop computer.
 * Serialized per computer (fixed port + one persistent profile per box), like
 * the probe. Throws on any failure — never leaving an unrecorded daemon
 * running.
 */
export async function ensureBrowserSession(
  deps: BrowserSessionDeps,
  args: EnsureBrowserSessionArgs,
): Promise<BrowserSessionHandle> {
  const { computerId } = await deps.reserveDesktop({
    bearer: args.bearer,
    projectId: args.projectId,
    signal: args.signal,
  });
  return withKeyedLock(`browser-session:${computerId}`, () =>
    ensureOnComputer(deps, computerId, args),
  );
}

/** Verify a looked-up row against the daemon itself; a handle on success. */
async function tryReuse(
  deps: BrowserSessionDeps,
  lookup: BrowserSessionLookup,
  signal?: AbortSignal,
): Promise<BrowserSessionHandle | null> {
  const session = lookup.session;
  if (!session) return null;
  const client = deps.createClient(session.publicOrigin, session.browserdToken);
  // Any transport failure counts as "not verified" — the relaunch path is the
  // recovery, so there is nothing better to do with the error.
  const status = await client.status().catch(() => null);
  if (!status || status.kind !== "ok" || status.bootId !== session.bootId) {
    return null;
  }
  // Best-effort: losing the touch costs an earlier sweep, never this turn.
  void deps.store
    .touch({ sessionId: session.sessionId, kind: "command", signal })
    .catch(() => {});
  return handleFromRecord(session, client, true);
}

function handleFromRecord(
  session: BrowserSessionRecord,
  client: SessionClient,
  reused: boolean,
): BrowserSessionHandle {
  return {
    sessionId: session.sessionId,
    computerId: session.computerId,
    bootId: session.bootId,
    client,
    streamUrl: session.streamUrl,
    streamPassword: session.streamPassword,
    contextMode: session.contextMode,
    reused,
  };
}

async function ensureOnComputer(
  deps: BrowserSessionDeps,
  computerId: string,
  args: EnsureBrowserSessionArgs,
): Promise<BrowserSessionHandle> {
  const bundleHash = deps.bundleHash();
  const contextMode = args.contextMode ?? "persistent";

  const lookup = await deps.store.lookup({
    computerId,
    expectedBundleHash: bundleHash,
    signal: args.signal,
  });
  const reusedHandle = await tryReuse(deps, lookup, args.signal);
  if (reusedHandle) return reusedHandle;

  // Relaunch. Everything below touches the sandbox; the connection is always
  // released, and a daemon that cannot be recorded is always stopped.
  const sandboxId = await deps.resolveSandboxId(computerId);
  const sandbox = await deps.connect(sandboxId);
  let handle: BrowserdHandle | undefined;
  try {
    await sandbox.killBrowserd();
    await sandbox.writeBundle(BROWSERD_SCRIPT_PATH, deps.bundle());
    try {
      handle = await deps.boot(sandbox.browserd, {
        scriptPath: BROWSERD_SCRIPT_PATH,
        port: BROWSERD_PORT,
        userDataDir: BROWSERD_USER_DATA_DIR,
      });
    } catch (bootError) {
      // Another replica may have won the boot race for this computer (the
      // keyed lock is per-process only): before failing, ask the store once
      // more and reuse a daemon that verifies.
      const retry = await deps.store.lookup({
        computerId,
        expectedBundleHash: bundleHash,
        signal: args.signal,
      });
      const raced = await tryReuse(deps, retry, args.signal);
      if (raced) return raced;
      throw bootError;
    }

    const { streamUrl, streamPassword } = await sandbox.ensureStream();

    const sessionId = await deps.store.record({
      computerId,
      bootId: handle.bootId,
      browserdToken: handle.bearer,
      browserdPort: handle.port,
      publicOrigin: handle.publicOrigin,
      streamUrl,
      streamPassword,
      bundleHash,
      contextMode,
      signal: args.signal,
    });
    if (!sessionId) {
      throw new Error(
        "browser session record did not land — refusing a runtime no replica could find",
      );
    }

    const booted = handle;
    handle = undefined; // recorded: the daemon now outlives this call
    return {
      sessionId,
      computerId,
      bootId: booted.bootId,
      client: deps.createClient(booted.publicOrigin, booted.bearer),
      streamUrl,
      streamPassword,
      contextMode,
      reused: false,
    };
  } finally {
    // On any failure after a boot, never leave an unrecorded daemon running;
    // never kill the durable computer itself.
    await handle?.stop().catch(() => {});
    await sandbox.disconnect().catch(() => {});
  }
}
