/**
 * HP-9 results matrix: host x capability -> where that fact actually came from.
 *
 * Reads the bundled catalog fallback (regenerated from the backend seed) and
 * renders a markdown audit table. Generated rather than hand-written so the
 * published matrix can never drift from the data the compat engine reads.
 *
 *   npx tsx scripts/report-capability-verification.ts            # print
 *   npx tsx scripts/report-capability-verification.ts --write    # write the doc
 *   npx tsx scripts/report-capability-verification.ts --check    # CI: fail if stale
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { bundledHostCompatCatalog } from "../src/host-compat/catalog.js";
import type { CapabilityProvenance } from "../src/host-compat/types.js";

const OUTPUT_PATH = path.resolve(
  process.cwd(),
  "../design-explorations/hp-9-capability-verification-matrix.md"
);

// Ordered so the levers a server developer actually gates on come first.
const DIMENSIONS = [
  "availableDisplayModes",
  "widgetDisplayModeRequests",
  "openLinks",
  "serverTools",
  "serverResources",
  "logging",
  "updateModelContext",
  "message",
  "downloadFile",
  "sandboxPermissions",
  "cspFrameDomains",
  "cspBaseUriDomains",
  "toolInfo",
  "toolInputPartial",
  "toolCancelled",
  "hostContextChanged",
  "resourceTeardown",
  "requestTeardown",
  "resourcePrefersBorder",
] as const;

const CELL: Record<CapabilityProvenance, string> = {
  observed: "**obs**",
  probe: "**pass**",
  "vendor-doc": "doc",
  assumed: "—",
  untestable: "n/a",
};

function main() {
  const catalog = bundledHostCompatCatalog();
  const hosts = Object.values(catalog.hostsById)
    .filter((host) => host.capabilityVerification)
    .sort((a, b) => a.id.localeCompare(b.id));

  const lines: string[] = [];
  lines.push("# HP-9 — capability verification matrix");
  lines.push("");
  lines.push(
    "Generated by `sdk/scripts/report-capability-verification.ts`. Do not edit by hand —",
    "regenerate after changing the backend seed.",
    ""
  );
  lines.push(
    "`**pass**` probe-captured against the real client · `doc` vendor-published ·",
    "`n/a` untestable (reason recorded in the seed) · `—` **assumed: no evidence**.",
    ""
  );

  // Coverage summary first — the number is the finding.
  let evidenced = 0;
  let total = 0;
  const perHost: string[] = [];
  for (const host of hosts) {
    const entries = Object.values(host.capabilityVerification ?? {});
    const backed = entries.filter(
      (e) => e.provenance === "probe" || e.provenance === "observed"
    ).length;
    const doc = entries.filter((e) => e.provenance === "vendor-doc").length;
    const untestable = entries.filter(
      (e) => e.provenance === "untestable"
    ).length;
    evidenced += backed + doc;
    total += entries.length;
    perHost.push(
      `| ${host.label} | \`${
        host.provenance
      }\` | ${backed} | ${doc} | ${untestable} | ${
        entries.length - backed - doc - untestable
      } |`
    );
  }

  lines.push("## Coverage");
  lines.push("");
  lines.push(
    `**${evidenced} of ${total} capability claims across ${hosts.length} MCP Apps hosts have any recorded evidence` +
      ` (${Math.round(
        (evidenced / total) * 100
      )}%).** The rest are values somebody chose that no` +
      " capture has ever confirmed."
  );
  lines.push("");
  lines.push(
    "| Host | Host provenance | Probed | Vendor doc | Untestable | Assumed |"
  );
  lines.push("| --- | --- | --- | --- | --- | --- |");
  lines.push(...perHost);
  lines.push("");

  lines.push("## Matrix");
  lines.push("");
  lines.push(`| Capability | ${hosts.map((h) => h.label).join(" | ")} |`);
  lines.push(`| --- | ${hosts.map(() => "---").join(" | ")} |`);
  for (const dimension of DIMENSIONS) {
    const cells = hosts.map((host) => {
      const entry = host.capabilityVerification?.[dimension];
      return entry ? CELL[entry.provenance] : "";
    });
    lines.push(`| \`${dimension}\` | ${cells.join(" | ")} |`);
  }
  lines.push("");

  lines.push("## Untestable dimensions");
  lines.push("");
  const untestableRows: string[] = [];
  for (const host of hosts) {
    for (const [dimension, entry] of Object.entries(
      host.capabilityVerification ?? {}
    )) {
      if (entry.provenance !== "untestable") continue;
      untestableRows.push(
        `| ${host.label} | \`${dimension}\` | ${entry.reason} |`
      );
    }
  }
  if (untestableRows.length === 0) {
    lines.push("_None._");
  } else {
    lines.push("| Host | Capability | Why it can't be exercised |");
    lines.push("| --- | --- | --- |");
    lines.push(...untestableRows);
  }
  lines.push("");

  const content = lines.join("\n");

  if (process.argv.includes("--check")) {
    const current = readFileSync(OUTPUT_PATH, "utf8");
    if (current !== content) {
      throw new Error(
        "Capability verification matrix is stale. Run `npx tsx scripts/report-capability-verification.ts --write`."
      );
    }
    return;
  }
  if (process.argv.includes("--write")) {
    writeFileSync(OUTPUT_PATH, content);
    return;
  }
  console.log(content);
}

main();
