/**
 * The Cursor CLI install, pinned.
 *
 * `@ai-sdk/harness-cursor`'s bootstrap runs `curl https://cursor.com/install |
 * bash`, and that script is regenerated for every Cursor release — it embeds
 * the build it downloads. So a hosted Cursor turn used to run whatever Cursor
 * had shipped that day, unverified, and two observed builds were four months of
 * behaviour apart. It was also why Cursor could not be baked into the computer
 * template: an image whose contents depend on the day it was built is not one a
 * recipe identity can describe.
 *
 * This module swaps that one file for an installer that downloads exactly the
 * pinned build from the same place Cursor's own script does and refuses it
 * unless its SHA-256 matches. The layout it produces is the vendor script's
 * (`$HOME/.local/share/cursor-agent/versions/<build>/` with `agent` and
 * `cursor-agent` symlinks in `$HOME/.local/bin`), so the adapter's
 * `implementation.json` (`executablePath: home/.local/bin/agent`) is untouched.
 *
 * To move the pin: install the new build from `cursor.com/install` on a scratch
 * box, take the `<build>` string and the two `agent-cli-package.tar.gz`
 * checksums (linux x64 and arm64), update {@link CURSOR_CLI_CHECKSUMS} and
 * `HARNESS_PINNED_VERSIONS.cursor` together, regenerate the bake lock, and
 * rebuild the computer template from that commit.
 */
import type { HarnessAgentAdapter } from "@ai-sdk/harness/agent";
import { HARNESS_PINNED_VERSIONS } from "@/shared/harness-model-support";

/** The pinned Cursor CLI build (what `agent --version` prints). */
export const CURSOR_CLI_VERSION: string = HARNESS_PINNED_VERSIONS.cursor;

/**
 * SHA-256 of `https://downloads.cursor.com/lab/<build>/linux/<arch>/
 * agent-cli-package.tar.gz`, per architecture the template builds for. Both
 * are recorded: an arm64 CI image verifies as strictly as the amd64 template.
 */
export const CURSOR_CLI_CHECKSUMS = {
  x64: "a79726c6e644520e993970be4c45775a6889802b67abe461a677a53219ae28e8",
  arm64: "785c5f6bf2a60eb1121e27ed8c14f5ee07ed1b5b6692324f2d9a997238245eb5",
} as const satisfies Record<string, string>;

/** The vendor installer's path inside the recipe, relative to `bootstrapDir`. */
const INSTALL_SCRIPT = "implementation/install.sh";

/** The download location, exactly as Cursor's own installer builds it. */
export function cursorCliDownloadUrl(
  arch: keyof typeof CURSOR_CLI_CHECKSUMS,
  version: string = CURSOR_CLI_VERSION,
): string {
  return `https://downloads.cursor.com/lab/${version}/linux/${arch}/agent-cli-package.tar.gz`;
}

/**
 * The pinned installer. Deterministic: the same inputs give the same bytes, so
 * the recipe identity (and therefore the baked marker) is stable.
 *
 * `set -euo pipefail` and a checksum gate BEFORE extraction: a truncated or
 * substituted archive must fail the install rather than land a binary that
 * runs with the customer's API key in its environment.
 */
export function renderPinnedCursorInstallScript(): string {
  const version = CURSOR_CLI_VERSION;
  return `#!/usr/bin/env bash
set -euo pipefail

# Pinned Cursor CLI ${version}. Generated by cursor-bootstrap.ts; do not edit.
ACP_IMPLEMENTATION_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
ACP_INSTALL_HOME="$ACP_IMPLEMENTATION_DIR/home"
export HOME="$ACP_INSTALL_HOME"
export PATH="$ACP_INSTALL_HOME/.local/bin:$PATH"

CURSOR_VERSION="${version}"
case "$(uname -m)" in
  x86_64|amd64) CURSOR_ARCH="x64"; CURSOR_SHA256="${CURSOR_CLI_CHECKSUMS.x64}" ;;
  arm64|aarch64) CURSOR_ARCH="arm64"; CURSOR_SHA256="${CURSOR_CLI_CHECKSUMS.arm64}" ;;
  *) echo "unsupported architecture $(uname -m)" >&2; exit 1 ;;
esac

mkdir -p "$ACP_INSTALL_HOME/.local/bin"
cd "$ACP_IMPLEMENTATION_DIR"

DOWNLOAD_DIR="$(mktemp -d)"
trap 'rm -rf "$DOWNLOAD_DIR"' EXIT
curl -fsSL "https://downloads.cursor.com/lab/\${CURSOR_VERSION}/linux/\${CURSOR_ARCH}/agent-cli-package.tar.gz" -o "$DOWNLOAD_DIR/agent.tar.gz"
echo "\${CURSOR_SHA256}  $DOWNLOAD_DIR/agent.tar.gz" | sha256sum -c -

FINAL_DIR="$ACP_INSTALL_HOME/.local/share/cursor-agent/versions/\${CURSOR_VERSION}"
rm -rf "$FINAL_DIR"
mkdir -p "$FINAL_DIR"
tar --strip-components=1 -xzf "$DOWNLOAD_DIR/agent.tar.gz" -C "$FINAL_DIR"

rm -f "$ACP_INSTALL_HOME/.local/bin/agent" "$ACP_INSTALL_HOME/.local/bin/cursor-agent"
ln -s "$FINAL_DIR/cursor-agent" "$ACP_INSTALL_HOME/.local/bin/agent"
ln -s "$FINAL_DIR/cursor-agent" "$ACP_INSTALL_HOME/.local/bin/cursor-agent"

test "$("$ACP_INSTALL_HOME/.local/bin/agent" --version)" = "\${CURSOR_VERSION}"
`;
}

/**
 * Wrap the Cursor adapter so its bootstrap installs the pinned, verified CLI.
 * Throws if the vendor recipe no longer ships an installer at the expected
 * path: a version bump that moves it must fail here, loudly, instead of
 * quietly shipping the unpinned `curl | bash`.
 */
export function pinCursorHarnessBootstrap(
  harness: HarnessAgentAdapter,
): HarnessAgentAdapter {
  const originalGetBootstrap = harness.getBootstrap?.bind(harness);
  if (!originalGetBootstrap) return harness;

  let cached:
    Awaited<ReturnType<NonNullable<typeof originalGetBootstrap>>> | undefined;

  return {
    ...harness,
    getBootstrap: async (...args) => {
      if (cached) return cached;
      const bootstrap = await originalGetBootstrap(...args);
      const installPath = `${bootstrap.bootstrapDir}/${INSTALL_SCRIPT}`;
      if (!bootstrap.files.some((file) => file.path === installPath)) {
        throw new Error(
          `the Cursor bootstrap no longer ships ${INSTALL_SCRIPT}; refusing to ` +
            "fall back to an unpinned install",
        );
      }
      cached = {
        ...bootstrap,
        files: bootstrap.files.map((file) =>
          file.path === installPath
            ? { ...file, content: renderPinnedCursorInstallScript() }
            : file,
        ),
      };
      return cached;
    },
  };
}
