name: Windows Release

on:
  push:
    tags:
      - 'v*'

jobs:
  make-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install
          npm run install:deps

      - name: Restore code signing cert
        if: ${{ secrets.WINDOWS_PFX_BASE64 != '' }}
        shell: pwsh
        run: |
          $bytes = [System.Convert]::FromBase64String($env:WINDOWS_PFX_BASE64)
          [IO.File]::WriteAllBytes("$env:RUNNER_TEMP\\codesign.pfx", $bytes)
        env:
          WINDOWS_PFX_BASE64: ${{ secrets.WINDOWS_PFX_BASE64 }}

      - name: Build
        run: npm run build

      - name: Make (Windows)
        env:
          WINDOWS_PFX_FILE: ${{ runner.temp }}\\codesign.pfx
          WINDOWS_PFX_PASSWORD: ${{ secrets.WINDOWS_PFX_PASSWORD }}
        run: npm run electron:make

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out\make\**\*Setup.exe
            out\make\**\RELEASES
            out\make\**\*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


