import { defineConfig } from "tsup";
export default defineConfig({
  entry: [
    "src/matchers.ts",
    "src/eval-tool-execution.ts",
    "src/predicates/argMatcher.ts",
    "src/predicates/evaluate.ts",
    "src/predicates/schema-validation.ts",
    "src/predicates/types.ts",
    "src/predicates/policy.ts",
    "src/predicates/transcript.ts",
    "src/predicates/index.ts",
    "src/contract/types.ts",
    "src/contract/adapters.ts",
    "src/contract/canonical.ts",
    "src/contract/derive.ts",
    "src/contract/policy-spelling.ts",
    "src/contract/evaluator-types.ts",
    "src/contract/evaluator-derive.ts",
    "src/scorers/types.ts",
    "src/scorers/concurrency.ts",
    "src/scorers/predicate-scorer.ts",
    "src/scorers/run.ts",
    "src/evaluators/assertion.ts",
    "src/evaluators/outcome.ts",
    "src/evaluators/run.ts",
    "src/evaluators/types.ts",
    "src/index.ts",
    "src/types.ts",
    "src/eval-reporting-types.ts",
  ],
  format: ["esm"],
  splitting: true,
  dts: true,
  clean: true,
  target: "es2022",
});
